version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
      - ./jupyter/requirements.txt:/temp/requirements.txt
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="  