version: '3'
name: malware_analysis
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./jupyter/Dockerfile
    volumes:
      - ./jupyter/work:/home/jovyan/work
      - ./jupyter/requirements.txt:/temp/requirements.txt
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="  
  
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock